### PR TITLE
Added limit to the max field

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by RyanThompson** [comment]
I think the max should be defaulted to 255 if not present as well: https://github.com/anomalylabs/text-field_type/blob/2.1/src/TextFieldType.php#L28

That make sense to you guys?

**Comment by Piterden** [comment]
Yep. Enough clean...

**Comment by Piterden** [comment]
Done

**Comment by huglester** [comment]
yeap, makes sense

**Pull request merged**
